# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]