version: "3.8"

services:
  localstack:
    container_name: "localstack-re-registration-service"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4588:4588"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=localhost
      - EDGE_PORT=4588
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/ar/run/docker.sock:/var/run/docker.sock"
