format_version: 4
pipelines:
  re-registration-service.build:
    group: repo-history
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          jobs:
            test_unit:
              resources:
                - docker
              artifacts:
                - build:
                    source: build
              tabs:
                test_report: build/reports/tests/test/index.html
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_unit
            test_integration:
              environment_variables:
                NHS_ENVIRONMENT: dev
              resources:
                - docker
              artifacts:
                - build:
                    source: build
              tabs:
                TestReport: build/reports/tests/integration/index.html
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_integration
            test_coverage:
              artifacts:
                - build:
                    source: build/reports/jacoco
              tabs:
                coverage: jacoco/test/html/index.html
                test_report: build/reports/tests/integration/index.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_coverage
            code_quality:
              artifacts:
                - build:
                    source: build/reports/spotbugs
              tabs:
                MainCodeQa: spotbugs/main/spotbugs.html
                TestCodeQa: spotbugs/test/spotbugs.html
                ITestCodeQa: spotbugs/integration/spotbugs.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks code_quality
      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: test_unit
                    source: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
