format_version: 4
common:
  plan_job: &plan_job
    resources:
      - docker
    artifacts:
      - build:
          source: terraform/nhs_deployment.tfplan
          destination: terraform/
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - fetch:
          stage: plan
          job: plan
          source: terraform/nhs_deployment.tfplan
          destination: terraform/
          is_file: yes
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
  common_stages: &common_stages
    - promote_docker_image:
        resources:
          - docker
        clean_workspace: true
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks promote_docker_image
    - plan:
        clean_workspace: true
        jobs:
          plan: *plan_job
    - deploy:
        clean_workspace: true
        jobs:
          deploy: *deploy_job
  prod_stages: &prod_stages
    - promote_docker_image:
        resources:
          - docker
        clean_workspace: true
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks promote_docker_image
    - plan:
        clean_workspace: true
        jobs:
          plan: *plan_job
    - deploy:
        approval:
          type: manual
          allow_only_on_success: true
        clean_workspace: true
        jobs:
          deploy: *deploy_job
pipelines:
  re-registration-service.dev:
    group: repo-history
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
      app:
        pipeline: re-registration-service
        stage: docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages: *common_stages

  re-registration-service.test:
    group: repo-history
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
      app:
        pipeline: re-registration-service
        stage: docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
      dev_env:
        pipeline: re-registration-service.dev
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: test
    stages: *common_stages

  re-registration-service.pre-prod:
    group: repo-history
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
      app:
        pipeline: re-registration-service
        stage: docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_pre_prod
      test_env:
        pipeline: re-registration-service.test
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
    stages: *common_stages

  re-registration-service.prod:
    group: repo-history
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
      app:
        pipeline: re-registration-service
        stage: docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_prod
      pre-prod_env:
        pipeline: re-registration-service.pre-prod
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: prod
    stages: *prod_stages
